# Generated by Django 5.1.1 on 2024-09-20 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('restaurant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_information', models.TextField(blank=True, null=True)),
                ('available_tables', models.IntegerField(blank=True, null=True, verbose_name='Available Tables')),
                ('opening_hours', models.CharField(blank=True, null=True, verbose_name='Opening Hours')),
                ('closing_hours', models.CharField(blank=True, null=True, verbose_name='Closing Hours')),
                ('cuisines', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('social_media_links', models.JSONField(blank=True, null=True, verbose_name='Social Media Links')),
                ('seating_capacity', models.IntegerField(blank=True, null=True, verbose_name='Seating Capacity')),
                ('unique_url', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('public_profile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_user', models.CharField(max_length=20)),
                ('booking_info', models.TextField(blank=True, null=True)),
                ('reservation_time', models.CharField(blank=True, null=True, verbose_name='Reservation Time')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('speech_to_text_notes', models.TextField(blank=True, null=True, verbose_name='Speech-to-Text Notes')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation')),
            ],
        ),
    ]
